# Generated by Django 4.2.5 on 2023-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_bloodgroup_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
