# Generated by Django 4.2.5 on 2023-10-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_getdonor_delete_bloodgroup_delete_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getdonor',
            old_name='district',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='district',
            new_name='address',
        ),
    ]
